/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.moroz.sample.service;

import org.springframework.stereotype.Component;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * Examples code for spring boot with CXF services. Hello is the interface for
 * sayHello interface. This class was generated by Apache CXF 3.1.0
 * 2015-05-18T13:02:03.098-05:00 Generated source version: 3.1.0
 */
@Component
@WebService(targetNamespace = "http://service.sample.moroz.com/", name = "hello")
public interface Hello {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "save",
                    targetNamespace = "http://service.sample.moroz.com/",
                    className = "com.moroz.sample.service.Save")
    @WebMethod(action = "urn:save")
    @ResponseWrapper(localName = "saveResponse",
                     targetNamespace = "http://service.sample.moroz.com/",
                     className = "com.moroz.sample.service.saveResponse")
    String save(@WebParam(name = "name", targetNamespace = "") String name,
                @WebParam(name = "lastName", targetNamespace = "") String lastName,
                @WebParam(name = "city", targetNamespace = "") String city);

    /*@WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "edit",
            targetNamespace = "http://service.sample.moroz.com/",
            className = "com.moroz.sample.service.Edit")
    @WebMethod(action = "urn:edit")
    @ResponseWrapper(localName = "editResponse",
            targetNamespace = "http://service.sample.moroz.com/",
            className = "com.moroz.sample.service.EditResponse")
    String edit(@WebParam(name = "id", targetNamespace = "") Long id);*/

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteById",
            targetNamespace = "http://service.sample.moroz.com/",
            className = "com.moroz.sample.service.DeleteById")
    @WebMethod(action = "urn:deleteById")
    @ResponseWrapper(localName = "deleteByIdResponse",
            targetNamespace = "http://service.sample.moroz.com/",
            className = "com.moroz.sample.service.DeleteByIdResponse")
    String deleteById(@WebParam(name = "id", targetNamespace = "") Long id);
}
